name: Cross-build raylib ARMv7 DRM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # do not change, it is Needed to push releases

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release raylib ARMv7 DRM

    steps:
    - name: Checkout this repo (for toolchain)
      uses: actions/checkout@v4

    - name: Clone raylib (shallow)
      run: git clone --depth 1 https://github.com/raysan5/raylib.git

    - name: Extract raylib version
      id: get_version
      run: |
        version=$(grep "#define RAYLIB_VERSION" raylib/src/raylib.h | awk '{print $3}' | tr -d '"')
        echo "version=${version}" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake ninja-build make git \
          gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
          libdrm-dev libgbm-dev libinput-dev \
          libgles2-mesa-dev

    - name: Create build directory
      run: mkdir build-raylib

    - name: Configure CMake
      working-directory: build-raylib
      run: |
        cmake ../raylib \
          -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-armv7-linux-gnueabihf.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DPLATFORM=DRM \
          -DUSE_OPENGL_ES=ON \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_GAMES=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -G Ninja

    - name: Build raylib
      working-directory: build-raylib
      run: ninja

    - name: Rename artifact
      run: |
        mkdir dist
        cp build-raylib/raylib/libraylib.a dist/libraylib-armv7-drm.a

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: Raylib-armv7-DRM-${{ steps.get_version.outputs.version }}
        name: Raylib-armv7-DRM ${{ steps.get_version.outputs.version }}
        files: dist/libraylib-armv7-drm.a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}