name: Cross-build raylib (ARMv7 + ARM64) DRM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7, arm64]
        include:
          - arch: armv7
            toolchain: Toolchain-armv7-linux-gnueabihf.cmake
            triple: arm-linux-gnueabihf
          - arch: arm64
            toolchain: Toolchain-aarch64-linux-gnu.cmake
            triple: aarch64-linux-gnu

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Clone raylib (shallow)
      run: git clone --depth 1 https://github.com/raysan5/raylib.git

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake ninja-build make git \
          gcc-${{ matrix.triple }} g++-${{ matrix.triple }} \
          libdrm-dev libgbm-dev libinput-dev \
          libgles2-mesa-dev

    - name: Create build directory
      run: mkdir build-${{ matrix.arch }}

    - name: Configure CMake for ${{ matrix.arch }}
      working-directory: build-${{ matrix.arch }}
      run: |
        cmake ../raylib \
          -DCMAKE_TOOLCHAIN_FILE=../cmake/${{ matrix.toolchain }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DPLATFORM=DRM \
          -DUSE_OPENGL_ES=ON \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_GAMES=OFF \
          -DBUILD_SHARED_LIBS=ON \
          -G Ninja

    - name: Build raylib (.a and .so)
      working-directory: build-${{ matrix.arch }}
      run: ninja

    - name: Package SDK-style tar.gz
      run: |
        mkdir -p raylib-${{ matrix.arch }}/include
        mkdir -p raylib-${{ matrix.arch }}/lib

        cp -r raylib/src/*.h raylib-${{ matrix.arch }}/include/
        cp build-${{ matrix.arch }}/raylib/libraylib.a raylib-${{ matrix.arch }}/lib/
        cp build-${{ matrix.arch }}/raylib/libraylib.so raylib-${{ matrix.arch }}/lib/

        DATE=$(date +'%d-%m-%Y')
        tar -czf Raylib-${{ matrix.arch }}-DRM\ (${DATE}).tar.gz raylib-${{ matrix.arch }}

    - name: Upload SDK tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: Raylib-${{ matrix.arch }}-DRM
        path: Raylib-${{ matrix.arch }}-DRM (*.tar.gz)