name: Cross-Build Raylib ARMv7 + ARM64 (Docker)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-raylib:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for cross-compilation
        run: docker build -t raylib-cross -f Dockerfile.cross-raylib .

      - name: Run cross-build in Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/build raylib-cross bash -c "
            set -eux

            git clone --depth 1 https://github.com/raysan5/raylib.git

            for arch in armv7 arm64; do
              if [ \"\$arch\" = \"armv7\" ]; then
                triple=arm-linux-gnueabihf
                toolchain_file=/usr/share/cmake-*/Modules/Platform/Linux-ARM.cmake
                target_arch=armhf
              else
                triple=aarch64-linux-gnu
                toolchain_file=/usr/share/cmake-*/Modules/Platform/Linux-AARCH64.cmake
                target_arch=arm64
              fi

              for platform in DRM Desktop; do
                folder=build-\$arch-\$platform
                mkdir \$folder && cd \$folder

                extra_flags=""
                if [ \"\$platform\" = \"PLATFORM_DRM\" ]; then
                  extra_flags=\"-DUSE_OPENGL_ES=ON\"
                fi

                cmake ../raylib \
                  -DCMAKE_SYSTEM_NAME=Linux \
                  -DCMAKE_SYSTEM_PROCESSOR=\$arch \
                  -DCMAKE_C_COMPILER=\$triple-gcc \
                  -DCMAKE_CXX_COMPILER=\$triple-g++ \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DPLATFORM=\$platform \
                  \$extra_flags \
                  -DBUILD_SHARED_LIBS=OFF \
                  -DBUILD_EXAMPLES=OFF \
                  -DBUILD_GAMES=OFF \
                  -G Ninja
                ninja

                cd ..
                sdk_dir=raylib-\$arch-\$(echo \$platform | tr '[:upper:]' '[:lower:]' | sed 's/platform_//')
                mkdir -p \$sdk_dir/include \$sdk_dir/lib
                cp -r raylib/src/*.h \$sdk_dir/include/
                cp \$folder/raylib/libraylib.a \$sdk_dir/lib/

                tar -czf \$sdk_dir.tar.gz \$sdk_dir
              done
            done
          "

      - name: Upload all SDKs
        uses: actions/upload-artifact@v4
        with:
          name: Raylib-SDKs
          path: raylib-*.tar.gz